src/classes/Ingredient.js, src/classes/Recipe.js, src/classes/RecipeRepository.js, src/classes/User.js, test/Ingredient-test.js, test/Recipe-test.js, test/User-test.js
Create initial commit after constructing class constructor and corresponding test files
=> Initial Commit

src/classes/Recipe.js, test/Recipe-test.js
What's this PR do? Add additional key value pairs to recipe constructor and add tests to Recipe-test.js
Where should the reviewer start? Run the tests and see if they work as intended.
How should this be manually tested? NPM test it!
=> Add additional key value pairs to recipe constructor and add tests to Recipe-test.js

test/Ingredient-test.js
Tests created for ingredient class
=> Add tests, verified passing

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request_template.md
⋅⋅* Add directory and files for issue templates
⋅⋅* Review files bug_report.md and feature_request_template.md
⋅⋅*  Hopefully should populate / be selectable when creating a new issue
⋅⋅* Created to help streamline processes and give more insight to issues / tasks
⋅⋅*  N/A
6. Questions:
⋅⋅* How are ya'll so awesome all the time? It's amazing, really.
=> Add dir for issue templates, files for bug reports and feature requests

src/classes/Recipe.js, src/data/ingredients.js, src/data/recipes.js, test/Ingredient-test.js, test/Recipe-test.js, test/User-test.js
⋅⋅*  Begins constructing methods for Recipe class. Focus on iterator for returning names.
⋅⋅*  Recipe.js line 1
⋅⋅*  run npm test test/Recipe-test.js
⋅⋅* 
⋅⋅* 
6. Questions:
⋅⋅*  How on earth do you run an iterator against 2 arrays at the same time?
=> Begin building Recipe methods

dist/index.html, src/styles.css
Added section/button/text rules to styles.css and refactored html
please take a look at the logo image, the path isn't working
visual review
=> Add section/button/text rules to styles.css and refactor html

dist/index.html, src/styles.css
recipe image boxes now work and fit the screen, same with the scrollbar
is there anything that could be DRYer?
resize your window, go crazy
=> Add scrollbar and boxes for recipe images, refactor margins/padding and HTML

src/classes/Recipe.js, test/Recipe-test.js
⋅⋅*  Creates functional methods in the recipe class for returning recipe ingredient names and instructions.
⋅⋅* line 1 Recipe.js
⋅⋅*  run npm test test/Recipe-test.js to test
⋅⋅*  Storing information across data sets using class instance objects was the key!
=> Finish 2/3 methods for Recipe

test/RecipeRepository-test.js
Add beforeEach and basic test skeleton to recipe repository test suite
Are there any more tests we should add?
visual review
=> Add beforeEach and basic test skeleton to recipe repository test suite

src/data/recipes-test.js, test/RecipeRepository-test.js
⋅⋅*  Add test data file for recipes and add import statement in RecipeRepository-test.js file
⋅⋅*  test/RecipeRepository-test.js then src/data/recipes-test.js
⋅⋅* Will be verified when unit testing
⋅⋅* This data file is a subset of src/data/recipes.js
⋅⋅* N/A
6. Questions:
⋅⋅* How's your day going?
=> Add test file and add import statement

src/classes/RecipeRepository.js, src/data/recipes-test.js, test/RecipeRepository-test.js
…
Condense beforeEach, add recipe data test, add RecipeRepository parameters
is it DRY enough?
run it in your terminal!
=> Condense beforeEach, add recipe data test, add RecipeRepository parameters

src/classes/RecipeRepository.js, src/data/recipes-test.js, test/Recipe-test.js, test/RecipeRepository-test.js
- Add the tag test and listRecipeTag method
- please take a look at this awesome method!
- test in your terminal to see the awesomeness!
⋅⋅*
=> Add the tag test and listRecipeTag method

src/classes/RecipeRepository.js, test/RecipeRepository-test.js
- This PR adds a function for listRecipeNames
⋅⋅* test/RecipeRepository-test.js then src/classes/RecipeRepository.js
⋅⋅* This method passes our testing logic
⋅⋅* Filters by tags :)
⋅⋅* N/A
6. Questions:
⋅⋅* What's your favorite color?
=> Add method listRecipeNames

src/classes/Recipe.js, src/classes/RecipeRepository.js, test/RecipeRepository-test.js
⋅⋅* Remove un-needed imports, remove comments, adjust spacing, add deep equal in test/RecipeRepository-test.js
⋅⋅* Anywhere :)
⋅⋅* Tests are still passing after updates/changes
⋅⋅* Just a little cleanup
⋅⋅* N/A
6. Questions:
⋅⋅* N/A
=> Remove un-needed imports, remove comments, adjust spacing

src/classes/User.js, test/User-test.js
Add pseudocode to the user class and 1 test + basic beforeEach skeleton to user test file
Please finish the beforeEach! Also, take a look at the pseudocode.
visual review, npm test
brb in an hour
=> Add pseudocode to the user class and 1 test + basic beforeEach skeleton to user test file

dist/index.html, src/styles.css
Creates the HTML elements for the recipe view
in index.html and styles.css. In index look for "recipe-view-container"
npm start to fire webpage and make sure the visual matches expectations
=> Create HTML elements and style for recipe view

src/classes/User.js, test/User-test.js
- Add user tests and addRecipeToCook method to user.js
- Please check out my addToCook method as well as added tests to the User-tests.js file
- Please review new methods in your console log
=> Add user tests and addRecipeToCook method to user.js

src/classes/User.js, test/User-test.js
- Refactor tests
- Add tests
- Add edits to class and addRecipesToCook
- RemoveRecipeToCook method 
- This method needs to be written!
⋅⋅* 
6. Questions:
⋅⋅*
=> Refactor and add tests to User-test file

src/data/users.js, src/scripts.js
Imports all files needed to scripts.js. Create the method that applies the name of the current user to the welcome message on load
3. Where should the reviewer start?
scripts.js
4. How should this be manually tested?
look at the live webpage and pull up the console to see console.logs
=> Finish welcome user function and import all files to scripts

src/classes/User.js, test/User-test.js
Add removeRecipeToCook function and relevant tests
Is the testing rigorous enough?
Add more test data, go crazy. Or don't.
=> Add removeRecipeToCook function and relevant tests

dist/index.html, src/scripts.js, src/styles.css
Writes methods that affect the dom in the home screen
in the webpage
open the webpage ad see the results
⋅⋅* 
⋅⋅* 
6. Questions:
⋅⋅*
=> Dom manipulation

README.md, dist/index.html, src/styles.css
-- Reorganize and add features to our README page
--Organize CSS
=> Add project README & organize CSS

dist/index.html, src/classes/Recipe.js, src/styles.css
Finish CSS and HTML construction for main home view
=> finalize CSS and HTML for home view

dist/index.html, src/styles.css
⋅⋅* Update HTML classes and ID names, add classes and css styling
⋅⋅* dist/index.html then src/styles.css
⋅⋅* Load web page locally and verify
=> Update class and IDs, add css and html sections

dist/index.html, src/scripts.js, src/styles.css
Add event listeners, query selectors, getelementbyids, show and hide functions, view functions; refactor classes and ids
Is there anything else we need to show or hide?
Navigate the pages!
=> Add event listeners, query selectors, getelementbyids, show and hide functions, view functions; refactor classes and ids

dist/index.html, src/scripts.js, src/styles.css
Cleans up CSS for home view and all recipes view. Found bug for trying to apply event listener to all recipe images/pic boxes
=> Bug: Cannot put event listener on all recipe images or boxes, getting error.

src/scripts.js, src/styles.css
Add hover effects to text, images, and buttons
Hover!
Does the pointer work?
Will change colors when we revamp the color scheme.
=> Add hover effects to text, images, and buttons

dist/index.html, src/styles.css
⋅⋅* This PR adds a button for saving recipes on the recipe view
⋅⋅* dist/index.html then src/styles.css
⋅⋅* Open locally and test
=> Add button for saving recipes

dist/index.html, src/classes/Recipe.js, src/classes/RecipeRepository.js, src/scripts.js, src/styles.css, test/RecipeRepository-test.js
creates the methods to be able to manipulate the dom so that a user can see all the detail of their chosen recipe in a specific recipe view.
click any recipe on the home page
=> Achieve functionality for displaying a chosen recipe by click

src/data/recipes.js, src/styles.css
affect the CSS styling of recipe images so the layout integrity persists across different screen sizes
=> CSS changes to ensure layout across all screen sizes

src/scripts.js
-- Add the getRandomRecipe function to scripts.js
-- Check out the randomized recipes on page load!
--Load the page
=> Add the getRandomRecipe function to scripts.js

src/scripts.js, src/styles.css
Add query selector, event listener and function for saving recipes
Push the button!
=> Add query selector, event listener and function for saving recipes

dist/index.html
-- Adds the cutest little browser tab icon
=> Add browser tab icon

src/scripts.js
Nothing, really... but also, _everything._
Add more project names to the array.
Don't worry about it.
=> Add page name randomizer array and function

README.md
-- Add features to our README.
-- Please check for spelling errors
-- The readme is finished.  All we need to do is add GIFs once our project is complete.
=> Add extra features to our README

src/scripts.js, src/styles.css
Add delete recipe function and event listener
Try deleting some stuff!
We still need to modify the button text.
=> Add delete recipe function and event listener

src/scripts.js
Enable save recipe button to change and revert inner text
Is it working?
=> Enable save recipe button to change and revert inner text

src/scripts.js
-- Allow a user to view the recipe card from the saved recipe view
=> Allow a user to view the recipe card from the saved recipe view

dist/index.html, src/scripts.js, src/styles.css
Created the filtered view for the filter functions. This allows the dom display of home view to remain intact while switching to another view
=> Created filtered view to keep dom manipulation separate from home view

dist/index.html, src/scripts.js, src/styles.css
Creates an additional input suite in the saved view to be able to use to filter saved recipes.
=> Creates additional filter buttons and input to be used in the saved view

dist/index.html, src/styles.css
- Add finishing touches on main section CSS and Header section
=> Add finishing touches on main section CSS and Header section

src/scripts.js
Creates the methods for filtering through our saved recipes by both name and tag.
=> Write filter functions for saved view

README.md
- Add google doc to READMME
- The only thing left is to add our Gif once our CSS is complete!
-Check out our awesome README page!
=> Add google doc to README

dist/index.html, src/scripts.js, src/styles.css
Refactored menu and image box CSS and html
Keep going!
=> Refactored menu and image box CSS and html

dist/index.html, src/scripts.js, src/styles.css
Remove all black borders, add additional page names, move save recipe button
Did this break anything?
=> Remove all black borders, add additional page names, move save recipe button

src/styles.css
-CSS refractor of styles: recipe centering, fonts, text color and size
=> CSS refactor

dist/index.html, src/scripts.js, src/styles.css
⋅⋅* 
⋅⋅* 
⋅⋅* 
⋅⋅* 
⋅⋅* 
6. Questions:
⋅⋅*
=> Add button stylings, add hovers, change colors slightly

src/styles.css
-Add css styling on trashcan
⋅⋅* 
⋅⋅* 
6. Questions:
⋅⋅*
=> Add CSS styling

src/styles.css
⋅⋅* Styling updates and general cleanup
⋅⋅* src/styles.css
⋅⋅* Verify in browser locally
⋅⋅* Pushed on Emma's behalf
=> Rename hover property and general cleanup

src/styles.css
Add styling to search button
⋅⋅* 
⋅⋅* 
⋅⋅* 
⋅⋅* 
6. Questions:
⋅⋅*
=> Add styling to search button

README.md
=> Add readme gif

README.md
-- Add Gif 
6. Questions:
-- I am able to run the GIF link through Atom but it does not show up on the project README.
-- Can anyone else see the link to the GIF?
=> Add GIF title to READMME

README.md
=> Add GIF to README

src/scripts.js
1) What's this PR do?
fixes bug where deleting saved recipes by hitting the trash icon didn't delete the recipe from the saved recipes array. Now it does, and the saved recipes view repopulates without the deleted recipe
=> Saved view bugfix3

dist/index.html, src/scripts.js
--Changes to en/ltr HTML tag
--Changes to form in HTML
--Changes to recipe images and woman holding plate image in scripts
=> Add semantic HTML to html and Scripts.js

src/scripts.js, src/styles.css
--Give all our recipe images an alt tag
--Change button color
=> Gives our website a 98 percent accessibility score!

dist/index.html
=> Final touchups on accessibility

src/scripts.js
Remove comments, refactor headings, modify indentation
=> Remove comments, refactor headings, modify indentation

src/classes/pantry.js
-- New pantry file! Please check out the class I created.  Do we use module.exports or export default?
=> Add pantry file to src file

src/classes/pantry.js
=> Small fix on pantry

src/classes/User.js
Refactor listRecipeToCookByTag and listRecipebyToCookName to be more DRY
=> Refactor listRecipeToCookByTag and listRecipebyToCookName to be more DRY

dist/index.html, src/scripts.js, src/styles.css
--Add hidden delete button to saved recipe button
--Add query selectors and event listeners
-- There is no functionality to this button yet.  We are still in the process of getting there
6. Questions:
--Any help would be great!
=> Add hidden delete button to saved recipes page

test/Pantry-test.js
Create Pantry-test file and describe/it blocks for each user story and method requirement
=> Create Pantry-test file and describe/it blocks for each user story and method requirement

src/classes/RecipeRepository.js, src/classes/User.js, test/RecipeRepository-test.js, test/User-test.js
⋅⋅* Add sad path methods and testing to verify error handling
⋅⋅* src/classes/RecipeRepository.js
⋅⋅* run an npm test locally
=> Add sad path methods and testing to verify error handling

dist/index.html, src/scripts.js, src/styles.css
Add deleteChosenRecipe function, modify saveChosenRecipe and HTML and CSS
=> Add deleteChosenRecipe function, modify saveChosenRecipe and HTML and CSS

src/classes/Pantry.js, test/Pantry-test.js
⋅⋅* Add method and testing for returnIngredientNamesAndAmounts for Pantry class
⋅⋅* test/Pantry-test.js
⋅⋅* npm test
⋅⋅* Test on line 168 of test/Pantry-test.js needs adjustment for text formatting
=> Add method and testing for returnIngredientNamesAndAmounts 

dist/index.html, src/classes/Pantry.js, src/scripts.js, src/styles.css
Add pantry view and related functions
Add pantry view and related functions
Add pantry view and related functions
Add pantry view and related functions
Add pantry view and related functions
6. Questions:
Add pantry view and related functions?
=> Add pantry view and related functions

src/classes/Pantry.js, test/Pantry-test.js
Creates the method that tells a user whether or not they will be able to cook a given recipe
=> Write pantry method to return whether a user can cook a recipe

src/classes/Pantry.js, test/Pantry-test.js
Now the method that returns whether a user can cook a recipe including the ingredient names and amounts missing to be able to cook it.
=> Refactor pantry method for returning if recipe can be cooked

src/classes/Pantry.js, test/Pantry-test.js
Refactors huge method to be more dynamic with iterator choices
=> Refactor returnIfRecipeIsCookable

dist/index.html, src/classes/Pantry.js, src/scripts.js
the user can click a check box in saved view, and the dom will update to tell them if they can cook the recipe. If not, it tells them how much of each ingredient they still need
=> Write dom manipulation for Pantry display in saved vew

dist/index.html, src/scripts.js
Correct save/delete button and message display behavior
=> Correct save/delete button and message display behavior

src/styles.css
--Add basic styling to the recipe view
=> Add css styling to recipe view

dist/index.html, src/scripts.js, src/styles.css
Add form and button and event listener for adding recipes
=> Add form and button and event listener for adding recipes

dist/index.html, src/scripts.js, src/styles.css
Creates the form and inputs for the pantry to be able to post ingredients
=> Create HTML elements for posting in pantry

src/apiCalls.js, src/scripts.js
Writes methods to POST to the User's pantry when an ingredient is added. Then the dom is updated automatically to reflect the changes
=> Write first of 2 POST methods to add ingredients to pantry

dist/index.html, src/scripts.js
Add cookRecipe FUNtion and related button and event listener
=> Add cookRecipe FUNtion and related button and event listener

dist/index.html, src/classes/Pantry.js, src/scripts.js, src/styles.css, test/Pantry-test.js
Implements the majority of error handling for the POST functions. However, there is still a bug that needs to be squashed when a user cooks a recipe they dont have enough ingredients for.
This also cleans up the formatting of all our files to be presentable for review
=> Implement error handling and general refactoring

src/scripts.js
⋅⋅* Fix issue where adding ingredients wiped out saved recipes
Submitted on Cole's behalf
=> Fix issue where adding ingredients wiped out saved recipes

dist/index.html, src/scripts.js, src/styles.css
--Add tabbing functionality to our page
=> Add tabbing functionality to our page

src/scripts.js
Creates the requisite code to error handle for all forms (No input or invalid input), and hides the cook button if a user cooks a recipe. Now, the user will never see the cook button unless they can cook a recipe
=> Make final error handling adjustments
